### ISSUE TITLE
make_fix_root_file() is no longer exported

### ISSUE THREAD

**Issue by jennybc** [krlmlr/rprojroot#10]
`make_fix_root_file()` is mentioned in some docs and in some `/dontrun{}`'d examples. It looks like it was once exported, but is not currently.

https://github.com/krlmlr/rprojroot/blob/55e850ed618b6b775b915c63e2f31333b213dbdb/R/file.R#L12

https://github.com/krlmlr/rprojroot/blob/55e850ed618b6b775b915c63e2f31333b213dbdb/R/file.R#L28

I see this has also come up here https://github.com/krlmlr/rprojroot/issues/9#issuecomment-181187650.

**Comment by krlmlr** [comment]
Thanks for reporting! This is what happens if you rely too much on automated testing ;-)
