### ISSUE TITLE
Evidence of git repo root dir as criterion

### ISSUE THREAD

**Issue by jennybc** [krlmlr/rprojroot#20]
Did I imagine this or was existence of `.git` at one point a more formally anticipated root criterion in rprojroot?

If it is not currently so, would you consider adding something like `is_git_repo()`? And including it in `here::here()`?

**Comment by krlmlr** [comment]
I think it's in the README, and also in #19. I'll take care of it in the next iteration, unless someone else does first.

**Comment by jennybc** [comment]
D'oh. Yes this is part of #19. I aspire to make a PR, so we'll if that happens before you come back around to it.
