### ISSUE TITLE
Recognize projectile projects?

### ISSUE THREAD

**Issue by jennybc** [krlmlr/rprojroot#21]
Might be closest analogue of seeking `foo.Rproj` for non-RStudio projects, e.g. ESS.

See also: https://github.com/krlmlr/here/issues/1

Hard to tell how much this would come up IRL though? Because it targets the intersection of "no rstudio", "not a package", and "no git". 🤔

**Comment by krlmlr** [comment]
I like the sentinel in krlmlr/here#1 as a general solution for niche use cases, but I'd be happy to review a PR.

**Comment by jennybc** [comment]
> the intersection of "no rstudio", "not a package", and "no git"

I suspect that is awfully close to the empty set. So I'll close this. If there is some enormous projectile user base, I assume you will hear from them!

**Comment by krlmlr** [comment]
Let's add it anyway.
