### ISSUE TITLE
Recommendation for use in a CRAN package?

### ISSUE THREAD

**Issue by jennybc** [krlmlr/rprojroot#22]
What's the official recommendation for expressing a package's dependence on rprojroot if it's used only in the tests?

I've built a test helper function so I can refer to test specimens easily in tests and access them during interactive development. Helper definition in `helper.R`:

``` r
test_sheet <- function(fname) find_testthat_root_file("sheets", fname)
```

Usage looks like this:

``` r
test_sheet("blanks.xls")
#> "/Users/jenny/rrr/readxl/tests/testthat/sheets/blanks.xls"
read_excel(test_sheet("blanks.xls"))
#> # A tibble: 2 × 2
#>       x     y
#>   <dbl> <chr>
#> 1    NA     a
#> 2     1  <NA>
```

`testthat.R` looks like this:

``` r
library(testthat)
library(readxl)

if (requireNamespace("rprojroot")) {
  test_check("readxl")
} else {
  message("Install suggested package rprojroot in order to run the tests.")
}
```

I've listed `rprojroot (>= 1.1)` in Suggests. Does this all look right?

**Comment by krlmlr** [comment]
`Suggests:` looks like the right place, and you can safely assume in the tests that the package is installed. (You'd check installation status if regular code accesses a suggested package.)
