### ISSUE TITLE
How to return directory of root containing .Rproj?

### ISSUE THREAD

**Issue by ndphillips** [krlmlr/rprojroot#23]
Thanks for your great package! I'm hoping this will be the end of my own working directory issues!

After going through your vignette (https://cran.r-project.org/web/packages/rprojroot/vignettes/rprojroot.html) I'm still having trouble solving a very simple problem: How can I use `rprojroot` to simply return the root directory as a string?

**Comment by krlmlr** [comment]
Just call the finder function without arguments. Example (for an R package):

```r
rprojroot::is_r_package$find_file()
```

Have you seen the `here` package? It offers a lighter-weight interface but might just work for most use cases.

**Comment by ndphillips** [comment]
Thanks! That did the trick. And no I hadn't seen the `here` package, I'll check it out!
