### ISSUE TITLE
Can rprojroot handle separated git directories?

### ISSUE THREAD

**Issue by karldw** [krlmlr/rprojroot#24]
Git [allows you](https://git-scm.com/docs/git-clone#git-clone---separate-git-dirltgitdirgt) to separate the .git folder from the project. For example:
```bash
git clone --separate-git-dir="$HOME/my_rprojroot.git" git@github.com:krlmlr/rprojroot.git
```
After running the command above, I have a .git **file** in the cloned rprojroot directory, which rprojroot doesn't recognize as a project criterion.

Could rprojroot handle separated git directories? One option would be changing [the code](https://github.com/krlmlr/rprojroot/blob/6d1069cd9fa2eed22364707c5e7be194d3e4ecdc/R/has-file.R#L126) to:
```r
is_git_root <- has_dir(".git") | has_file(".git", contents = "^gitdir: ")
```
If that sounds good, I can pull together a PR.

**Comment by krlmlr** [comment]
Thanks, a PR would be great. In which lines of the `.git` file can the `gitdir` string appear?

**Comment by karldw** [comment]
I think it's always created as a one-line file, but I'm not positive.  (Here's the [source](https://github.com/git/git/blob/d6db3f216544d05e09159756812ccbcb16861d71/builtin/init-db.c#L333).)

`.git` can also be a symbolic link to a file or directory, but `file.exists`, `readLines` and `dir.exists` already follow symbolic links, so that should be fine. 
(`has_file(contents = ...)` eventually calls to `readLines`.)
