### ISSUE TITLE
How to use with testthat?

### ISSUE THREAD

**Issue by BarkleyBG** [krlmlr/rprojroot#29]
I can't figure out how to load the `rprojroot` library when running `devtools::test()`.

I'm pushing a MWE repo soon to https://github.com/BarkleyBG/rprojrootTester

Basically, I've:

1. Added `library(rprojroot)` to the `tests/testthat.R` file 
2. Added `rprojroot` to "suggests" in the description
3. Created a unit test script, `test_myFun.R` under `tests/testthat` directory
4. Added two calls to the unit test script:
   - one to `rprojroot::find_testthat_root_file()`. This works as intended.
   - one to `find_testthat_root_file()` without the prefix `rprojroot::`. This throws an error.

Am I missing something about where to call `library(rprojroot)`?

**Comment by BarkleyBG** [comment]
The MWE is up; Please let me know if anything's unclear, or if I can be of further help.

**Comment by jennybc** [comment]
There is no guarantee that all ways you might run tests will first source `tests/testthat.R`. I think there *might* be such a guarantee re: a `tests/helper.R` file?

In any case, I usually just use this style to call rprojroot functions in my tests: `rprojroot::find_testthat_root_file()`. If it's coming up a lot, I might create my own helper function in `helper.R` and, in the body, have a call to `rprojroot::find_testthat_root_file()`.

**Comment by BarkleyBG** [comment]
Ahh, I see what you mean by the helper functions now!

I do wonder if this issue could be remedied with a `use_rprojroot()` function in the long term.

 - Brian

Sent from my phone; please excuse any typos


On Oct 31, 2017, at 6:30 PM, Jennifer (Jenny) Bryan <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no guarantee that all ways you might run tests will first source tests/testthat.R. I think there might be such a guarantee re: a tests/helper.R file?

In any case, I usually just use this style to call rprojroot functions in my tests: rprojroot::find_testthat_root_file(). If it's coming up a lot, I might create my own helper function in helper.R and, in the body, have a call to rprojroot::find_testthat_root_file().

**Comment by BarkleyBG** [comment]
Holy cow, thanks @jennybc for the suggestion about the `tests/testthat/helper.R` script! I had never known that `testthat` did that. What a GREAT find.

I solved barkleybg/rprojrootTester#1 by adding `library(rprojroot)` to the `helper.R` file. 
WOW. SO EASY! THANKS.


I'll try to find some time this weekend to add this new bit of information to #26. Thanks for your patience 🎃
