### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by jennybc** [krlmlr/rprojroot#7]
Someone just drew my attention to my gist where I read your comment and came here. It feels like I have never read that comment or come here. Or I am losing my mind? Hate that gist comments don't notify :(

Anyhow, glad to have found this! I look forward to trying it out.

Sorry to crap up your issues with this.

**Comment by krlmlr** [comment]
Thanks for the heads up. I didn't know that gists don't notify.

This project has been idle/stable for long enough now, I guess I should push it to CRAN at some point.

If you like this, you might also find `kimisc::thisfile()` useful -- this is a hack that lets `.R` script files know their own name.

**Comment by jennybc** [comment]
OK I'll check out `kimisc` too.
